DefaultContentLanguage: de
pluralizelisttitles: false
PygmentsCodeFences: true
PygmentsUseClasses: true
languageCode: "de"
DisqusShortname: "ceisendle"
languages:
  de:
    title: de 
    weight: 1
    LanguageName: Deutsch
    title: Das Brotokoll - Christian's Rezeptesammlung
    menu:
      main:
        - name: Brot und Gebäck
          title: Brot und Gebäck
          identifier: Brot und Gebäck
          weight: 10
          url: /post/brot/
        - name: Süßes
          title: Süßes
          identifier: Süßes
          weight: 100
          url: /post/suesses/

author:
  name: "Christian's Brotokoll"
params:
  sidebar: "left"
  github: "https://github.com/christianeisendle"
  twitter: "https://twitter.com/ceisendle"
  home: "Startseite"
  tagline: ""
  theme: "theme-base-0b"
  hideReadingTime: true
  truncate: false